version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.20

release-args: &release-args
  mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml -PbuildKar
  ssh-fingerprints: "73:40:5d:60:85:c4:02:7e:79:10:30:6e:36:8d:4b:02"
  context: rso-base
  filters:
    branches:
      only: master

jobs:
  build_and_test:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - maven/with_cache:
          verify_dependencies: false
          steps:
            - run:
                name: Run Maven Build
                command: |
                  mvn clean --batch-mode verify -PbuildKar -Dit
      - run:
          name: Save test results
          command: |
            mkdir -p ~/project/artifacts/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
            mkdir -p ~/project/artifacts/it-reports/
            find . -type f -regex ".*/target/it-reports/.*" -exec cp {} ~/project/artifacts/it-reports/ \;
          when: always
      - store_test_results:
          path: ~/project/artifacts/junit
      - store_artifacts:
          path: ~/project/artifacts/it-reports


workflows:
  build-branch:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          <<: *release-args

  release-from-master:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - build_and_test
          <<: *release-args
