version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.5
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.15

workflows:
  build-and-test:
    jobs:
      - github-maven-deploy/build-and-test:
          mvn-build-test-command: mvn clean verify -PbuildKar -Dit
          mvn-collect-artifacts-command: |
            mkdir -p ~/project/artifacts/junit/
            cp ~/project/nexus-repository-composer/target/surefire-reports/*.xml ~/project/artifacts/junit/
            cp ~/project/nexus-repository-composer/target/nexus-repository-* ~/project/artifacts/
            cp ~/project/nexus-repository-composer/target/failsafe-reports/*.xml ~/project/artifacts/junit/
  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml -PbuildKar
          requires:
            - approve-release
          ssh-fingerprints: "73:40:5d:60:85:c4:02:7e:79:10:30:6e:36:8d:4b:02"
          context: rso-base
          mvn-release-prepare-command: |
            mvn -PbuildKar --batch-mode release:prepare -DscmCommentPrefix="[skip ci] [maven-release-plugin] "
          filters:
            branches:
              only: master
